apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: lab
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lab-admin
  namespace: default
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lab-admin-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: lab
roleRef:
  kind: Role
  name: lab-admin
  apiGroup: rbac.authorization.k8s.io